BEGIN;

DROP TABLE IF EXISTS "monster",
"category";



-- CREATION DES TABLES --


CREATE TABLE "monster" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "category_id" integer NOT NULL REFERENCES "category"("id"), -- Attention à bien créer la table category avec id dedans --
);

-- continuer ensuite --